"""Mapeo identificado: columna cruda -> (ticker Bloomberg, campo, ajuste, tipo).
ajuste: 'none' = sin ajustes, 'split' = solo splits, 'default' = default terminal.
tipo: 'mercado' (diario, calce exacto esperado), 'fundamental' (revisable), 'macro' (revisable, fecha de periodo),
      'derivada' (se calcula desde otra serie)."""

MAPPING = {
    "SPY US Equity (CLOSE)":     ("SPY US Equity", "PX_LAST", "none", "mercado"),
    "SPY US Equity (OPEN)":      ("SPY US Equity", "PX_OPEN", "none", "mercado"),
    "SPY US Equity (HIGH)":      ("SPY US Equity", "PX_HIGH", "none", "mercado"),
    "SPY US Equity (LOW)":       ("SPY US Equity", "PX_LOW", "none", "mercado"),
    "SPY US Equity (VOLUME)":    ("SPY US Equity", "PX_VOLUME", "none", "mercado"),
    "BIL US Equity (Risk Free)": ("FDTR Index", "PX_LAST", "none", "mercado"),
    "SPY US Equity":             ("NAPMPMI Index", "PX_LAST", "default", "macro"),
    "QQQ US Equity":             ("NAPMNMI Index", "PX_LAST", "default", "macro"),
    "IWM US Equity":             ("XLF US Equity", "PX_LAST", "none", "mercado"),
    "EFA US Equity":             ("XLK US Equity", "PX_LAST", "split", "mercado"),
    "EEM US Equity":             ("XLE US Equity", "PX_LAST", "split", "mercado"),
    "VGK US Equity":             ("XLV US Equity", "PX_LAST", "none", "mercado"),
    "EWJ US Equity":             ("XLI US Equity", "PX_LAST", "none", "mercado"),
    "FXI US Equity":             ("XLY US Equity", "PX_LAST", "split", "mercado"),
    "DXY Curncy":                ("XLP US Equity", "PX_LAST", "none", "mercado"),
    "EURUSD Curncy":             ("XLU US Equity", "PX_LAST", "split", "mercado"),
    "USDJPY Curncy":             ("XLB US Equity", "PX_LAST", "split", "mercado"),
    "FNERTR Index":              ("XLRE US Equity", "PX_LAST", "none", "mercado"),
    "XLF US Equity":             ("IWM US Equity", "PX_LAST", "none", "mercado"),
    "XLK US Equity":             ("IWD US Equity", "PX_LAST", "none", "mercado"),
    "XLE US Equity":             ("IWF US Equity", "PX_LAST", "none", "mercado"),
    "XLV US Equity":             ("MDY US Equity", "PX_LAST", "none", "mercado"),
    "XLI US Equity":             ("DIA US Equity", "PX_LAST", "none", "mercado"),
    "XLU US Equity":             ("QQQ US Equity", "PX_LAST", "none", "mercado"),
    "GDP CQOQ Index":            ("GDP CQOQ Index", "PX_LAST", "default", "macro"),
    "NAPMPMI Index":             ("IP CHNG Index", "PX_LAST", "default", "macro"),
    "CONSSENT Index":            ("CPMINDX Index", "PX_LAST", "default", "macro"),  # PMI manufacturero China (NBS)
    "NFP TCH Index":             ("USURTOT Index", "PX_LAST", "default", "macro"),
    "USURTOT Index":             ("NFP TCH Index", "PX_LAST", "default", "macro"),
    "CPI YOY Index":             ("INJCJC Index", "PX_LAST", "default", "macro"),
    "PCE CRCH Index":            ("INJCSP Index", "PX_LAST", "default", "macro"),
    "RSTAMOM Index":             ("CPI YOY Index", "PX_LAST", "default", "macro"),
    "LEI TOTL Index":            ("CPUPXCHG Index", "PX_LAST", "default", "macro"),
    "INJCJC Index":              ("PCE CYOY Index", "PX_LAST", "default", "macro"),
    "NHSPSTOT Index":            ("PPI YOY Index", "PX_LAST", "default", "macro"),
    "IP CHNG Index":             ("RSTAMOM Index", "PX_LAST", "default", "macro"),
    "CONCCONF Index":            ("CONCCONF Index", "PX_LAST", "default", "macro"),
    "NAPMNMI Index":             ("CONSSENT Index", "PX_LAST", "default", "macro"),
    "Extra E15":                 ("NHSPSTOT Index", "PX_LAST", "default", "macro"),
    "ETSLTOTL Index":            ("ETSLTOTL Index", "PX_LAST", "default", "macro"),
    "GDP CYOY Index":            ("NHSPATOT Index", "PX_LAST", "default", "macro"),
    "CPTICHNG Index":            ("LEI TOTL Index", "PX_LAST", "default", "macro"),
    "PITLCHNG Index":            ("DGNOXTCH Index", "PX_LAST", "default", "macro"),  # ordenes bienes duraderos ex transporte MoM
    "FDTR Index":                ("USGG3M Index", "PX_LAST", "default", "mercado"),
    "GB3 Govt":                  ("USGG2YR Index", "PX_LAST", "none", "mercado"),
    "GB6 Govt":                  ("USGG5YR Index", "PX_LAST", "default", "mercado"),
    "GB12 Govt":                 ("USGG10YR Index", "PX_LAST", "none", "mercado"),
    "GT2 Govt":                  ("USGG30YR Index", "PX_LAST", "default", "mercado"),
    "GT5 Govt":                  ("USYC2Y10 Index", "PX_LAST", "none", "mercado"),
    "GT10 Govt":                 ("USYC3M10 Index", "PX_LAST", "none", "mercado"),
    "GT30 Govt":                 ("LF98OAS Index", "PX_LAST", "none", "mercado"),
    "USGG10YR Index":            ("LUACOAS Index", "PX_LAST", "default", "mercado"),
    "CL1 Comdty":                ("SPX Index", "PE_RATIO", "default", "fundamental"),
    "HO1 Comdty":                ("SPX Index", "PX_TO_BOOK_RATIO", "default", "fundamental"),
    "GC1 Comdty":                ("SPX Index", "EARN_YLD", "default", "fundamental"),
    "SI1 Comdty":                ("SPX Index", "BEST_PE_RATIO", "default", "fundamental"),
    "GLD US Equity":             ("IVE US Equity", "PX_LAST", "none", "mercado"),
    "SLV US Equity":             ("IVW US Equity", "PX_LAST", "none", "mercado"),
    "USO US Equity":             ("GLD US Equity", "PX_LAST", "none", "mercado"),
    "DBC US Equity":             ("SLV US Equity", "PX_LAST", "none", "mercado"),
    "DBA US Equity":             ("DBC US Equity", "PX_LAST", "none", "mercado"),
    "BCOMTR Index":              ("USO US Equity", "PX_LAST", "none", "mercado"),
    "GSCITR Index":              ("UNG US Equity", "PX_LAST", "all", "mercado"),
    "VIX Index":                 ("VIX Index", "PX_LAST", "none", "mercado"),
    "VIX3M Index":               ("VIX3M Index", "PX_LAST", "none", "mercado"),
    "VIX1M Index":               ("VIX6M Index", "PX_LAST", "default", "mercado"),
    "VXV Index":                 ("VIX1Y Index", "PX_LAST", "default", "mercado"),
    "VXEEM Index":               ("VVIX Index", "PX_LAST", "default", "mercado"),
    "VXEFA Index":               ("SKEW Index", "PX_LAST", "default", "mercado"),
    "GVZ Index":                 ("UX1 Index", "PX_LAST", "default", "mercado"),
    "OVX Index":                 ("UX2 Index", "PX_LAST", "default", "mercado"),
    "TYVIX Index":               ("MOVE Index", "PX_LAST", "none", "mercado"),
    "MOVE Index":                ("CVIX Index", "PX_LAST", "none", "mercado"),
    "CVIX Index":                ("OVX Index", "PX_LAST", "none", "mercado"),
    "VIY1 Index":                ("GVZ Index", "PX_LAST", "none", "mercado"),
    "V2X Index":                 ("VXEEM Index", "PX_LAST", "none", "mercado"),
    "AAII BULLISH Index":        ("PCUSEQTR Index", "PX_LAST", "default", "mercado"),
    "PUT Index":                 ("HYG US Equity", "PX_LAST", "none", "mercado"),
    "NYHL Index":                ("LQD US Equity", "PX_LAST", "none", "mercado"),
    "TICK Index":                ("TLT US Equity", "PX_LAST", "none", "mercado"),
    "TRIN Index":                ("IEF US Equity", "PX_LAST", "none", "mercado"),
    "ADD Index":                 ("SHY US Equity", "PX_LAST", "none", "mercado"),
    "MCCL Index":                ("EFA US Equity", "PX_LAST", "none", "mercado"),
    "MCSU Index":                ("EEM US Equity", "PX_LAST", "none", "mercado"),
    "SRVOL Index":               ("FXI US Equity", "PX_LAST", "none", "mercado"),
    "PCUSEQUI Index":            ("DXY Curncy", "PX_LAST", "none", "mercado"),
    "USGG2YR Index":             ("USGG2YR Index", "PX_LAST", "none", "mercado"),
    "USYC2Y10 Index":            ("USYC2Y10 Index", "PX_LAST", "none", "mercado"),
    "USYC3M10 Index":            ("USYC3M10 Index", "PX_LAST", "none", "mercado"),
    "US0003M Index":             ("US0003M Index", "PX_LAST", "none", "mercado"),
    "USSWAP10 Index":            ("USSWAP10 Index", "PX_LAST", "none", "mercado"),
    "CDX IG CDSI GEN 5Y":        ("CDX IG CDSI GEN 5Y Corp", "PX_LAST", "none", "mercado"),
    "CDX HY CDSI GEN 5Y":        ("CDX HY CDSI GEN 5Y Corp", "PX_LAST", "none", "mercado"),
    "LF98TRUU Index":            ("LF98TRUU Index", "PX_LAST", "none", "mercado"),
    "LF98OAS Index":             ("LF98OAS Index", "PX_LAST", "none", "mercado"),
    "LUACTRUU Index":            ("LUACTRUU Index", "PX_LAST", "none", "mercado"),
    "LQD US Equity":             ("LQD US Equity", "PX_LAST", "none", "mercado"),
}
