# -*- coding: utf-8 -*-
"""
Regenerates app/backend/data/ JSON files from current pipeline results.

Reads pre-computed positions and returns from backtest_detail.pkl
(generated by optimize_and_backtest.py) plus trained_artifacts.pkl for
dates and market data. Produces models_summary.json, daily_data.json,
market_data.json, and regime_data.json.
"""

import json
import os
import pickle
import numpy as np
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS_DIR = os.path.join(BASE_DIR, "models")
RESULTS_DIR = os.path.join(BASE_DIR, "results")
BACKEND_DATA_DIR = os.path.join(BASE_DIR, "app", "backend", "data")

INSTRUMENTS = {
    'UPRO': {'expense_ratio': 0.0091, 'bid_ask': 0.0005},
    'SPY': {'expense_ratio': 0.0009, 'bid_ask': 0.0002},
    'CASH': {'expense_ratio': 0.0000, 'bid_ask': 0.0000},
}

MODEL_CATEGORIES = {
    'Ridge': 'ML', 'Lasso': 'ML', 'ElasticNet': 'ML',
    'RandomForest': 'ML', 'GradientBoosting': 'GradientBoosting',
    'XGBoost': 'GradientBoosting', 'LightGBM': 'GradientBoosting',
    'CatBoost': 'GradientBoosting',
    'ExponentialSmoothing': 'TimeSeries', 'Theta': 'TimeSeries',
    'SeasonalNaive': 'TimeSeries', 'AutoARIMA': 'TimeSeries',
    'Prophet': 'Specialized', 'GARCH': 'Specialized',
    'DLinear': 'DeepLearning', 'NBEATS': 'DeepLearning',
    'NHiTS': 'DeepLearning', 'TCN': 'DeepLearning', 'TFT': 'DeepLearning',
    'CNN_LSTM': 'RNN', 'LSTM_Attention': 'RNN',
    'BiLSTM': 'RNN', 'BiGRU': 'RNN',
}


def extract_trades(positions, strategy_returns, market_returns, dates, predictions, percentiles,
                    expense_costs=None, trading_costs=None, vol_drag_costs=None):
    """Extract individual trades from position changes."""
    trades = []
    n = len(positions)
    pos_to_inst = {3: 'UPRO', 1: 'SPY', 0: 'CASH'}
    trade_id = 0

    i = 0
    while i < n:
        entry_idx = i
        entry_pos = int(positions[i])
        cum_return = 1.0
        cum_market = 1.0
        trade_expense = 0.0
        trade_trading = 0.0
        trade_vol_drag = 0.0

        j = i
        while j < n and positions[j] == entry_pos:
            cum_return *= (1 + strategy_returns[j])
            cum_market *= (1 + market_returns[j])
            if expense_costs is not None:
                trade_expense += expense_costs[j]
            if trading_costs is not None:
                trade_trading += trading_costs[j]
            if vol_drag_costs is not None:
                trade_vol_drag += vol_drag_costs[j]
            j += 1

        exit_idx = j - 1
        trade_id += 1
        tx_cost = trade_expense + trade_trading + trade_vol_drag
        trade_dict = {
            'trade_id': trade_id,
            'entry_date': dates[entry_idx],
            'entry_idx': entry_idx,
            'entry_position': entry_pos,
            'entry_instrument': pos_to_inst.get(entry_pos, 'CASH'),
            'entry_prediction': float(predictions[entry_idx]),
            'entry_percentile': float(percentiles[entry_idx]),
            'exit_date': dates[exit_idx],
            'exit_idx': exit_idx,
            'duration': exit_idx - entry_idx + 1,
            'total_return': float(cum_return - 1),
            'market_return': float(cum_market - 1),
            'tx_cost': float(tx_cost),
            'costs': {
                'expense': float(trade_expense),
                'trading': float(trade_trading),
                'vol_drag': float(trade_vol_drag),
            },
        }
        trades.append(trade_dict)
        i = j

    return trades


def classify_regimes(market_returns, window=60):
    """Classify each day into a market regime using rolling window."""
    n = len(market_returns)
    regimes = []
    for i in range(n):
        if i < window:
            regimes.append('unknown')
            continue
        w = market_returns[i-window:i]
        cum_return = float(np.prod(1 + w) - 1)
        vol = float(np.std(w) * np.sqrt(252))
        if cum_return > 0.10 and vol < 0.20:
            regime = 'bull'
        elif cum_return < -0.10:
            regime = 'bear'
        elif vol > 0.25:
            regime = 'high_vol'
        else:
            regime = 'sideways'
        regimes.append(regime)
    return regimes


def main():
    print("=" * 80)
    print("UPDATING BACKEND DATA FROM PIPELINE RESULTS")
    print("=" * 80)

    # Load pipeline data
    print("\n[1] Loading pipeline data...")
    with open(os.path.join(MODELS_DIR, "trained_artifacts.pkl"), 'rb') as f:
        artifacts = pickle.load(f)

    # Load pre-computed backtest detail (positions, returns, etc.)
    detail_path = os.path.join(RESULTS_DIR, "backtest_detail.pkl")
    with open(detail_path, 'rb') as f:
        detail = pickle.load(f)
    detail_models = detail['models']

    # Load optimal params for display values
    with open(os.path.join(RESULTS_DIR, "optimal_model_params.json"), 'r') as f:
        optimal_params = json.load(f)

    metadata = artifacts['metadata']
    y_test = np.array(metadata['forward_returns_test'][:-1])
    rf_test = np.array(metadata['risk_free_test'][:-1])
    all_test_dates = metadata.get('dates_test', metadata.get('test_dates', []))
    # forward_returns[i] = return realized from day i close -> day i+1 close
    # Shift dates forward by 1 so each row shows the date the return was realized
    n_ret = len(y_test)
    if len(all_test_dates) > n_ret:
        test_dates = all_test_dates[1:n_ret + 1]
    else:
        test_dates = all_test_dates[:n_ret]
    date_strs = [str(d)[:10] for d in test_dates]

    n_days = len(y_test)
    n_years = n_days / 252
    print(f"    Models: {len(detail_models)}, Days: {n_days}")

    # Benchmark: SPY B&H neto del expense ratio (0.09%/ano), consistente con el
    # paper y con optimize_and_backtest.py (spy_bh_net = fwd - expense/252)
    spy_daily_net = y_test - INSTRUMENTS['SPY']['expense_ratio'] / 252
    spy_equity = np.cumprod(1 + spy_daily_net)
    spy_return = float(spy_equity[-1] - 1)
    spy_cagr = float((1 + spy_return) ** (252 / n_days) - 1)
    rf_annual = float(np.mean(rf_test) * 252)
    spy_annual_vol = float(np.std(y_test) * np.sqrt(252))
    spy_sharpe = float((spy_cagr - rf_annual) / spy_annual_vol) if spy_annual_vol > 0 else 0.0
    spy_running_max = np.maximum.accumulate(spy_equity)
    spy_max_dd = float(np.max((spy_running_max - spy_equity) / spy_running_max))
    spy_drawdown = (spy_equity - spy_running_max) / spy_running_max

    # Process each model using pre-computed data
    print("\n[2] Processing models...")
    models_summary = []
    daily_data = {}

    for model_name, md in detail_models.items():
        # Read pre-computed arrays from backtest_detail.pkl
        positions = np.array(md['positions'])
        percentiles = np.array(md['percentiles'])
        predictions = np.array(md['predictions'])
        strategy_returns = np.array(md['strategy_returns'])
        gross_returns = np.array(md['gross_returns'])
        equity_curve = np.array(md['equity_curve'])
        drawdown_arr = np.array(md['drawdown'])
        daily_costs = np.array(md['daily_costs'])
        expense_costs = np.array(md['expense_costs'])
        trading_costs = np.array(md['trading_costs'])
        vol_drag_costs = np.array(md['vol_drag_costs'])

        min_len = len(positions)

        # Compute metrics from pre-computed returns
        equity = equity_curve
        running_max = np.maximum.accumulate(equity)

        total_ret = float(equity[-1] - 1)
        annual_ret = float((1 + total_ret) ** (1/n_years) - 1) if n_years > 0 else 0
        annual_vol = float(np.std(strategy_returns) * np.sqrt(252))
        sharpe = float((annual_ret - rf_annual) / annual_vol) if annual_vol > 0 else 0
        rf_daily = np.mean(rf_test[:min_len])
        downside = strategy_returns - rf_daily
        downside = np.minimum(downside, 0)
        downside_vol = float(np.sqrt(np.mean(downside**2)) * np.sqrt(252))
        sortino = float((annual_ret - rf_annual) / downside_vol) if downside_vol > 0 else 0
        max_dd = float(np.max((running_max - equity) / running_max))
        calmar = float(annual_ret / abs(max_dd)) if abs(max_dd) > 0 else 0

        pred_dir = np.sign(predictions[:min_len])
        actual_dir = np.sign(y_test[:min_len])
        da = float(np.mean(pred_dir == actual_dir))

        pct_3x = float(np.mean(positions == 3) * 100)
        pct_1x = float(np.mean(positions == 1) * 100)
        pct_cash = float(np.mean(positions == 0) * 100)
        n_trades = int(np.sum(np.diff(positions) != 0))

        # Trades
        trades = extract_trades(positions, strategy_returns, y_test[:min_len],
                                date_strs[:min_len], predictions, percentiles,
                                expense_costs, trading_costs, vol_drag_costs)
        active_trades = [t for t in trades if t['entry_position'] != 0]
        winning = [t for t in active_trades if t['total_return'] > 0]
        losing = [t for t in active_trades if t['total_return'] <= 0]
        win_rate = len(winning) / len(active_trades) if active_trades else 0
        avg_win = float(np.mean([t['total_return'] for t in winning])) if winning else 0
        avg_loss = float(np.mean([t['total_return'] for t in losing])) if losing else 0
        profit_factor = abs(avg_win / avg_loss) if avg_loss != 0 else 0

        # Dollar costs
        gross_equity = np.cumprod(1 + gross_returns)
        initial_capital = 10000
        gross_final = initial_capital * gross_equity[-1]
        final_capital = initial_capital * equity[-1]
        dollar_costs = float(gross_final - final_capital)

        category = MODEL_CATEGORIES.get(model_name, 'Other')

        # Display params from optimal_model_params.json (most common KNN combo)
        model_params = optimal_params.get(model_name, {})
        params = model_params.get('params', {'q_long_extreme': 10, 'q_long_moderate': 30})
        q_3x = params.get('q_long_extreme', 10)
        q_1x = params.get('q_long_moderate', 30)

        # Signal quality info (from characteristics if available)
        chars = model_params.get('characteristics', {})
        pct_signal = chars.get('pct_signal_days', 100)

        model_summary = {
            'model': model_name,
            'category': category,
            'beat_spy': total_ret > spy_return,
            'total_return': total_ret,
            'annual_return': annual_ret,
            'market_return': spy_return,
            'excess_return': total_ret - spy_return,
            'sharpe': sharpe,
            'sortino': sortino,
            'calmar': calmar,
            'max_drawdown': -abs(max_dd),
            'annual_volatility': annual_vol,
            'directional_accuracy': da,
            'pct_3x': pct_3x,
            'pct_1x': pct_1x,
            'pct_cash': pct_cash,
            'pct_long': pct_3x + pct_1x,
            'n_trades': n_trades,
            'win_rate': win_rate,
            'avg_win': avg_win,
            'avg_loss': avg_loss,
            'profit_factor': profit_factor,
            'total_costs': dollar_costs,
            'initial_capital': 10000,
            'final_capital': float(final_capital),
            'profit_loss': float(final_capital - 10000),
            'n_days': min_len,
            'n_years': float(n_years),
            'params': {'q_3x': q_3x, 'q_1x': q_1x},
            'pct_signal_days': float(pct_signal),
            # Aliases expected by generate_paper_tables.py
            'dir_accuracy': da,
            'mean_position': float(np.mean(positions)),
            'final_equity': float(final_capital),
            'transaction_costs': dollar_costs,
        }
        models_summary.append(model_summary)

        # Metrics dict for /api/models/{name}/metrics and /api/compare
        metrics_dict = {
            'total_return': total_ret,
            'annual_return': annual_ret,
            'market_return': spy_return,
            'excess_return': total_ret - spy_return,
            'sharpe': sharpe,
            'sortino': sortino,
            'calmar': calmar,
            'max_drawdown': -abs(max_dd),
            'annual_volatility': annual_vol,
            'win_rate': win_rate,
            'dir_accuracy': da,
            'mean_position': float(np.mean(positions)),
            'n_trades': n_trades,
            'n_days': min_len,
            'pct_long': pct_3x + pct_1x,
            'pct_3x': pct_3x,
            'pct_1x': pct_1x,
            'pct_cash': pct_cash,
            'transaction_costs': dollar_costs,
            'pct_signal_days': float(pct_signal),
        }

        daily_data[model_name] = {
            'category': category,
            'params': {'q_3x': q_3x, 'q_1x': q_1x},
            'dates': date_strs[:min_len],
            'trades': trades,
            'predictions': predictions.tolist(),
            'percentiles': percentiles.tolist(),
            'positions': positions.tolist(),
            'strategy_returns': strategy_returns.tolist(),
            'market_returns': y_test[:min_len].tolist(),
            'equity_curve': equity.tolist(),
            'market_equity': spy_equity[:min_len].tolist(),
            'drawdown': drawdown_arr.tolist(),
            'daily_costs': daily_costs.tolist(),
            'risk_free': rf_test[:min_len].tolist(),
            'metrics': metrics_dict,
        }

        beat = "BEATS SPY" if total_ret > spy_return else ""
        print(f"    {model_name:<20} Ret: {total_ret*100:+7.1f}% Sharpe: {sharpe:+6.3f} DA: {da*100:.1f}% {beat}")

    # Save models_summary.json
    beating_spy = [m for m in models_summary if m['beat_spy']]
    summary_output = {
        'timestamp': datetime.now().isoformat(),
        'strategy': 'LONG-ONLY (0, +1, +3)',
        'methodology': 'Meta-KNN dynamic thresholds + signal quality filter',
        'config': {'window': 63, 'initial_capital': 10000},
        'test_period': {'start': date_strs[0], 'end': date_strs[-1], 'n_days': n_days},
        'benchmark': {
            'total_return': spy_return,
            'sharpe': spy_sharpe,
            'max_drawdown': -spy_max_dd,
            'final_value': float(spy_equity[-1] * 10000),
            'spy_final_value': float(spy_equity[-1] * 10000),
        },
        'models_beating_spy': len(beating_spy),
        'total_models': len(models_summary),
        'models': sorted(models_summary, key=lambda x: x['total_return'], reverse=True),
    }

    out_path = os.path.join(BACKEND_DATA_DIR, "models_summary.json")
    with open(out_path, 'w') as f:
        json.dump(summary_output, f, indent=2)
    print(f"\n[OK] {out_path}")

    # Save daily_data.json
    out_path = os.path.join(BACKEND_DATA_DIR, "daily_data.json")
    with open(out_path, 'w') as f:
        json.dump(daily_data, f)
    print(f"[OK] {out_path}")

    # Update market_data.json with current dates/equity
    market_output = {
        'dates': date_strs,
        'returns': y_test.tolist(),
        'equity_curve': spy_equity.tolist(),
        'drawdown': spy_drawdown.tolist(),
    }
    out_path = os.path.join(BACKEND_DATA_DIR, "market_data.json")
    with open(out_path, 'w') as f:
        json.dump(market_output, f)
    print(f"[OK] {out_path}")

    # Generate regime_data.json
    print("\n[4] Generating regime data...")
    regimes = classify_regimes(y_test)

    regime_counts = {}
    for r in regimes:
        regime_counts[r] = regime_counts.get(r, 0) + 1

    # Per-model performance in each regime
    regime_performance = {}
    for model_name, data in daily_data.items():
        strat_rets = np.array(data['strategy_returns'])
        model_regimes = {}
        for regime_name in ['bull', 'bear', 'sideways', 'high_vol']:
            mask = np.array([r == regime_name for r in regimes[:len(strat_rets)]])
            regime_days = int(np.sum(mask))
            if regime_days > 0:
                regime_rets = strat_rets[mask]
                regime_total = float(np.prod(1 + regime_rets) - 1)
            else:
                regime_total = 0.0
            model_regimes[regime_name] = {
                'total_return': regime_total,
                'n_days': regime_days,
            }
        regime_performance[model_name] = model_regimes

    regime_output = {
        'current_regime': regimes[-1] if regimes else 'unknown',
        'regime_counts': regime_counts,
        'regime_performance': regime_performance,
    }
    out_path = os.path.join(BACKEND_DATA_DIR, "regime_data.json")
    with open(out_path, 'w') as f:
        json.dump(regime_output, f, indent=2)
    print(f"[OK] {out_path}")
    print(f"    Regimes: {regime_counts}")

    print(f"\n{'='*80}")
    print(f"Backend data updated. {len(models_summary)} models, {len(beating_spy)} beat SPY.")
    print(f"{'='*80}")


if __name__ == "__main__":
    main()
